### ISSUE TITLE
[enhancement] List name in title for when we bookmark a page

### ISSUE THREAD

**Issue by ghost** [lockys/awesome-search#106]
When I bookmark one of the page the default is "Awesome Search". It should be (example) "Awesome Search - awesome-flexbox"

**Comment by lockys** [comment]
Yap, that would be good! 
Thanks for the recommendation.

**Comment by carolinaknoll** [comment]
Hello, can I take this one for Hacktoberfest? I'm not sure just yet, but I might be able to come up with something for this.

Normally, when you bookmark a page, the name of the bookmark is the same as the title of the page. 

What I am thinking of doing is, when an user clicks an awesome list, the page title will also change, just like the example @pouledodue suggested above.

Thank you! 😄

**Comment by lockys** [comment]
Hi, @carolinaknoll - np, you can take this project and do anything you want. I'm running out of time and unable to work on this project by now(I hope to refresh the UI at sometimes :P). I'm very happy if you are willing to enhance this project in any aspect. If possible, share me with the work you will do in Hacktoberfest. :)

**Comment by carolinaknoll** [comment]
Awesome, thanks! 🎉
