### ISSUE TITLE
Too wide viewport

### ISSUE THREAD

**Issue by RinatValiullov** [lockys/awesome-search#108]
Fix please in the left area after serching.
![image](https://user-images.githubusercontent.com/9755333/36213034-6a669360-11c7-11e8-943f-b439e3847ae8.png)

**Comment by lockys** [comment]
late for the reply, I'm hoping to bring new UI to this project.
But I think it'd be a quick fix for this bug when I'm free.
Also Please feel free to have PR if you are available! 😭

**Comment by carolinaknoll** [comment]
Hello, turns out I am having this problem too.

Can I take this to work on it for Hacktoberfest?

Thank you! 😄
