### ISSUE TITLE
Search indexing non-awesome lists

### ISSUE THREAD

**Issue by 0xInfection** [lockys/awesome-search#109]
https://awesomelists.top/#/repos/{anyuser}/{any repo}

Open this URL with any user with any repo and it will get the README file irrespective of whether they are an awesome list or not.

On the other hand where this system should search for only awesome lists.

**Comment by 0xInfection** [comment]
Is this project dead? Like the build is failing, issues are not being looked after. What is the dev doing?

**Comment by lockys** [comment]
Yes, this project does not block that behavior at this time... You can have any repo to be shown under https://awesomelists.top.
