### ISSUE TITLE
jnv/list provides list in csv format.

### ISSUE THREAD

**Issue by lockys** [lockys/awesome-search#13]
https://github.com/jnv/lists/blob/gh-pages/lists.csv

**Comment by inputsh** [comment]
Not complete (or, not using https://github.com/sindresorhus/awesome as a source).

There's a mention to only one list from my profile, even though I'm maintaining three lists listed in https://github.com/sindresorhus/awesome.

**Comment by lockys** [comment]
:+1:  This project uses `sindresohus/awesome` as source.
