### ISSUE TITLE
"Back to Awesome" link does not work on awesomelists.me

### ISSUE THREAD

**Issue by eush77** [lockys/awesome-search#3]
`<- Back to Awesome` link redirects to `/awesome-search` which works when the page URL is http://lockys.github.io/awesome-search/ and fails with 404 code if it is http://awesomelists.me/.

**Comment by eush77** [comment]
@lockys It looks like you [applied some changes](https://github.com/lockys/awesome-search/commit/c3e72f3c012a0da0f4a50342df14ab0ea6376373) from #4 to fix this. So I guess it should work now.

**Comment by lockys** [comment]
@eush77 Yes, it fixed now. Sorry for the late reply, Thanks for your PR and helping! I will take a look at your PR and evaluate if the `History API` is a better way to achieve this :)
