### ISSUE TITLE
Decrease the transparency a bit

### ISSUE THREAD

**Issue by inputsh** [lockys/awesome-search#52]
![screenshot from 2015-12-08 17 12 50](https://cloud.githubusercontent.com/assets/4890548/11660774/03099ac8-9dcf-11e5-8a9c-11e9c8e97dcf.png)

This is way too transparent. Maybe something like .8 or .9 would be better.

**Comment by lockys** [comment]
Thanks for your suggestion :+1:  fix it in #54 
Let me know if there are problems.
