### ISSUE TITLE
Readmes for some lists are not rendered correctly

### ISSUE THREAD

**Issue by eush77** [lockys/awesome-search#6]
One example is [awesome-talks](https://github.com/JanVanRyswyck/awesome-talks).

In particular, `marked` doesn't seem to recognize the same syntax for headings as GitHub:

``` js
> marked('#Awesome talks')
'<p>#Awesome talks</p>\n'
> marked('# Awesome talks')
'<h1 id="awesome-talks">Awesome talks</h1>\n'
```

**Comment by lockys** [comment]
Yes, I noticed some syntax of Markdwon which `markded` can not recognize :cry:  
I will try another markdwon processor, or if you have any suggestions, please let me know that :)
