### ISSUE TITLE
vhf/free-programming-books is not searchable

### ISSUE THREAD

**Issue by vhf** [lockys/awesome-search#89]
Hey, awesome project you got there!

It seems only the readme is searchable. My repo got tons of files which serve different spoken languages and purposes.

Could we work something out?

Thanks!

**Comment by lockys** [comment]
Hi, @vhf  nice to see you here :100:.
For now, `awesome-search` only exacts the links in the `readme` file of awesome repos.
However, it will cause problem in some repos that put awesome resources in different markdown files or some repos with different language versions.

It will be definitely nice to let users search in `vhf/free-programming-books`.
I will try to come up with a appropriate solution to achieve this recently.
[algolia](https://community.algolia.com/docsearch/) recently announces a doc search service which does a nice job in searching text in a website, I am also thinking if it is possible to integrate with doc search by algolia.
If you have any idea about this, I am very happy to hear your opinion :) 
Thanks a lot!
