### ISSUE TITLE
show when each list was last updated

### ISSUE THREAD

**Issue by pokeball99** [lockys/awesome-search#95]
best way to do this is likely github api commits

**Comment by lockys** [comment]
Sorry for lately reply.
I have thought about this :+1:, will be added 
Or any contributions :)

**Comment by aschrijver** [comment]
Ah, I just created the same issue at [the wrong location](https://github.com/sindresorhus/awesome/issues/709) and was about to create it here:

> Awesome project is awesome, but a big drawback to me is that it is hard to see which entries have been added since the last time I checked. So I often find myself checking the commits, and even the code changes if the commit message was unclear.
> 
> Just like the awesome badge there should be a script that marks entries with a consistent 'NEW' label when they are committed and subsequently checks whether other 'NEW' labels in the list still deserve that label. There could be a configurable time an entry is considered new (e.g. 30 days by default).

**Comment by lockys** [comment]
@aschrijver  Thanks for the recommendations.
Yes, I think it's features that could be added into the `AwesomeSearch`.
I would wait for someone's PR if anyone see this. 
If not, I will added these features by my own later as I have some others that need to work now 😢

**Comment by aschrijver** [comment]
Unfortunately I lack the time to do this myself, and also still fairly unfamiliar with TravisCI and the best way to implement this in a way that is as portable as possible across all awesome lists.
But I am sure many people will find this a truly _awesome_ feature :wink:

**Comment by lockys** [comment]
check out the new version here.
https://lockys.github.io/AwesomeSearchReact
